"""update connection

Revision ID: 2185c697fad4
Revises: 494b06a63c41
Create Date: 2025-10-21 11:56:38.255328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2185c697fad4'
down_revision: Union[str, Sequence[str], None] = '494b06a63c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_legislation', 'authority_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_data_legislation_authority_'), table_name='data_legislation')
    op.drop_column('data_legislation', 'authority_')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_legislation', sa.Column('authority_', postgresql.ENUM('PRESIDENT', 'GOVERNMENT', 'STATE', 'MVD', 'CIVIL_DEFENSE', 'MID', 'SNG', 'MO', 'SVTS', 'STEK', 'ASS', 'MU', 'SIN', 'SSP', 'OK', 'SDK', 'AVC', 'PAK', 'FDS', 'FSB', 'FSVNG', 'FSKON', 'FSO', 'SVR', 'FSFM', 'GYSPP', 'YDP', 'MZ', 'FSNSZ', 'FMBA', 'MK', 'FAA', 'FAT', 'MNVO', 'MON', 'SNSON', 'FADM', 'MPRE', 'SGMOS', 'SNP', 'AVR', 'ALH', 'AN', 'MPT', 'MP', 'ATRM', 'MRDVA', 'MCRSMK', 'MSMK', 'SNSSITMK', 'APMK', 'AG', 'MSH', 'SVFN', 'FAR', 'MS', 'MSJKH', 'FPP', 'MT', 'FSNST', 'FAVT', 'FDA', 'FAJT', 'FAMRT', 'MTSZ', 'FSRZ', 'MF', 'FNS', 'FSFBN', 'FK', 'MER', 'FSA', 'FSGRKK', 'FSIS', 'FAGR', 'FAYGI', 'ME', 'FAS', 'FSGS', 'FMS', 'FSNZPP', 'GGSV', 'FSRAR', 'FSKATR', 'FTS', 'FST', 'FSETAN', 'FKA', 'FANO', 'FADN', 'FAOGG', 'FSS', 'FFOMS', 'PF', 'FPSS', 'PPF', 'SP', 'SK', 'CB', 'GP', 'GPR', 'RAN', name='authoritytype'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_data_legislation_authority_'), 'data_legislation', ['authority_'], unique=False)
    op.alter_column('data_legislation', 'authority_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
