"""update type biginteger to str

Revision ID: 3bab275d36d1
Revises: 2185c697fad4
Create Date: 2025-10-21 14:05:14.634470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bab275d36d1'
down_revision: Union[str, Sequence[str], None] = '2185c697fad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_legislation', 'publication_number',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=512),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_legislation', 'publication_number',
               existing_type=sa.String(length=512),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
