"""update name char 4096

Revision ID: 403ec9e87975
Revises: 4b2912d0d4d2
Create Date: 2025-10-20 16:58:02.966375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '403ec9e87975'
down_revision: Union[str, Sequence[str], None] = '4b2912d0d4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_legislation', 'name',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=4096),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_legislation', 'name',
               existing_type=sa.String(length=4096),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###
