"""add connections

Revision ID: 494b06a63c41
Revises: 403ec9e87975
Create Date: 2025-10-21 11:31:23.459465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494b06a63c41'
down_revision: Union[str, Sequence[str], None] = '403ec9e87975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_legislation', sa.Column('authority_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_data_legislation_authority'), table_name='data_legislation')
    op.create_index(op.f('ix_data_legislation_authority_'), 'data_legislation', ['authority_'], unique=False)
    op.create_index(op.f('ix_data_legislation_authority_id'), 'data_legislation', ['authority_id'], unique=False)
    op.create_foreign_key(None, 'data_legislation', 'authorities', ['authority_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_legislation', type_='foreignkey')
    op.drop_index(op.f('ix_data_legislation_authority_id'), table_name='data_legislation')
    op.drop_index(op.f('ix_data_legislation_authority_'), table_name='data_legislation')
    op.create_index(op.f('ix_data_legislation_authority'), 'data_legislation', ['authority_'], unique=False)
    op.drop_column('data_legislation', 'authority_id')
    # ### end Alembic commands ###
