"""add binary_pdf

Revision ID: 79e4fd253158
Revises: 3bab275d36d1
Create Date: 2025-10-21 14:53:31.812828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e4fd253158'
down_revision: Union[str, Sequence[str], None] = '3bab275d36d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_legislation', sa.Column('binary_pdf', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_legislation', 'binary_pdf')
    # ### end Alembic commands ###
