"""add law_number

Revision ID: c3fadd3aa19c
Revises: 79e4fd253158
Create Date: 2025-10-28 10:17:01.155159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3fadd3aa19c'
down_revision: Union[str, Sequence[str], None] = '79e4fd253158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_legislation', sa.Column('law_number', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_data_legislation_law_number'), 'data_legislation', ['law_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_legislation_law_number'), table_name='data_legislation')
    op.drop_column('data_legislation', 'law_number')
    # ### end Alembic commands ###
